sonar.projectKey=qa-raiders-lanchonete
sonar.projectName=QA Raiders - Lanchonete Online
sonar.projectVersion=1.0

sonar.sources=src/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=1.8

sonar.host.url=http://localhost:9000
